<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_KatalonExercises</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b2a061cc-7387-45e5-9ac8-3c261c88929b</testSuiteGuid>
   <testCaseLink>
      <guid>39fbfbb8-0f9c-432c-9445-5c2191ada6b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB01-Verify Checkboxes</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58c1256b-1953-4980-9b3b-aa1d4e53302e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b78aad66-ed53-4983-92bd-c9864a4d6403</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB02-Verify Drag And Drop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c61e2cf1-033d-4bcb-80c7-97d6f295cc62</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>11bf666b-47a4-43d8-8888-c388008c8e3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB03-Verify Dropdown</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc4ace88-0b92-4e26-a798-2dfc13c91f5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fb2c82f-7350-4700-93ae-8360accf4026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>360455a6-77d2-4aad-95dd-58266176549d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c6818d7-4d1c-49ee-8660-057f7ea894e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB04-Verify File Upload</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ea3b9f3-9d98-4db6-8b7a-7ca6973b22c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99afb65-b517-4db9-88d2-ceceb804ea73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbabd68f-7f84-4139-ac93-c54103fec873</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8284526-381f-4e79-bb00-c7170c8befd3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>656a3b48-e75f-4d39-98dc-0a374bb21878</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB05-Verify Frames</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aafbaebf-f952-4b7f-b494-57222b1fb81a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf1a04c1-4f70-4ba3-bb22-f531ceb96bd7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83aaaa3a-0c97-42e2-a7d9-513a99add11d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB06-Verify Alert</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55f56c6b-d53d-45b1-9e12-8361445d2f82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8e0a320-cf4a-4bd3-8c56-5bb0885604b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9a2f261-b5fb-46b9-bbc9-6f463b82c958</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c22244d4-0d74-4960-9fd3-09ab28e15a42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c44ca71f-0c26-4acf-ae3c-b7040696c325</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>252df5d4-e7ce-45b3-ae3f-5b3fff201e65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7b4cf38-1724-4103-9fc3-1219eddbf660</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB07-Verify Key Press</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07f85467-fb9d-4cf3-b8f5-6214406b7a70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>945cb763-ee9d-45a0-b8ba-6d7c624fa3b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>583a6df5-beaa-4360-a8e0-2233ddc9d2ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f41566e-5832-42bd-9042-d5a384b7b3d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3c9cc09-b81f-4324-96ca-5da2c96445ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB08-Verify Color And Font</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61134da6-a65a-4195-8c13-2f2563b71e7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a9f4d08-e448-4b34-81a4-ae2cd72ebca3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>935fef4f-7080-4363-a6d6-d901565b99ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB09-Verify Slider</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7afe1755-b9b8-4a36-8313-adb7a17e08e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c5b8435-4e28-4c4f-8142-d9aa15afda7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d32d48f2-4099-4ae6-8db9-ff1262e233aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>729781bb-396b-480a-bf35-459c7756fdbb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b072950-9214-44da-8edd-39994e209ccc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB10-Verify Menu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>055e20ad-94ee-4cab-b9d9-4d4c593711a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59d9bde8-7d1d-4b5d-acf7-71517753789f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>deab4328-7e0c-4284-a14e-fb4b3c036d32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf8966a0-2216-479f-9f1d-fd02c0822abd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7aeef3c-6229-414b-b040-2812c3b01b80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainTC/WTC-UIB11-Verify Table</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c99cf90a-17cd-4bd9-913c-641216b8a4a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43b2a993-8c5c-456e-be61-a2f96eeca677</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8dce27d-5a8c-4d57-8e34-85df3cfa1d20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5261627c-9841-48e6-ba2f-570222254b50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f03cc5d8-6c0d-43f7-bf69-3f84039428b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f03c0690-2251-4da4-8b01-baee61c427cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>151b5aaa-c685-477b-8ba6-3fa419200de2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44405a0c-25b1-4608-9cad-6445571fdb5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddd17b11-9875-4cbc-bdeb-898d9bbcb71a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad87d93f-52f0-4f88-8266-0c02ce6ecfa3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8a6db59-c7cc-48a3-b0b7-ee74c05cf173</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
