<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbl_BodyEmailColumnTable2</name>
   <tag></tag>
   <elementGuidId>a3fffb3f-c644-40a0-b775-1f9a41d7049b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='table2']/tbody//tr[${RowIndex}]//td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='table2']/tbody//tr[${RowIndex}]//td[3]</value>
   </webElementProperties>
</WebElementEntity>
