<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbl_EmailColumnTable2</name>
   <tag></tag>
   <elementGuidId>1415407e-e421-4ba0-a923-f4532e3d7c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='table2']/thead//tr[1]//th[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='table2']/thead//tr[1]//th[3]</value>
   </webElementProperties>
</WebElementEntity>
