<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbl_HeaderRow</name>
   <tag></tag>
   <elementGuidId>ac968c77-38e1-4b31-a8eb-3277d1504f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='table1']//tr[1]//th[${ColumnIndex}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='table1']//tr[1]//th[${ColumnIndex}]</value>
   </webElementProperties>
</WebElementEntity>
